---
# This file is designed for sanity checking of the container
# 
# Do not use it for production.
version: "3"

services:
  snipe:
    image: "quay.io/littlemanco/snipe-it:latest"
    build: "."
    ports: 
      - "80:80"
      - "443:443"
    env_file:
      - ".env.docker-compose"
    depends_on:
      - "mysql"
  mysql:
    image: "mysql:5.7"
    environment:
      # Mysql Parameters
      MYSQL_ROOT_PASSWORD: "thisisthemysqlrootpassword"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "thisisthemysqlsnipepassword"
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
  # Responsible for installing the database.
  #
  # See https://github.com/snipe/snipe-it/issues/4152
  snipe-init:
    image: "quay.io/littlemanco/snipe-it:latest"
    env_file:
      - ".env.docker-compose"
    depends_on:
      - "mysql"
      - "snipe"
    user: "www-data"
    command:
      - "php"
      - "/var/www/snipe/artisan"
      - "migrate"
      - "--force"
    restart: "on-failure"

